### ISSUE TITLE
Parameter estimation with 4 data sets

### ISSUE THREAD

**Issue by GeorgeLoizou** [GMPtk/RVis#4] opened 2019-12-10 11:44 UTC
Imported 4 urinary metabolite excretion data sets for use in parameter estimation module. Set target accept rate to 0.4. Click on "Iterate" and the the "Stop" button is momentarily enabled before returning to Iterate. Simulation does not initiate.

![Param_estimation_4_data_sets_no_sim](https://user-images.githubusercontent.com/11518130/70526749-34738980-1b42-11ea-89fb-376ae58721b1.png)

**Comment by thehoglet** [comment] 2019-12-10 13:13
The cause of this is in [McmcChain](https://github.com/GMPtk/RVis/blob/fbf8c767f7f8b0221cc927adc016674ea6e10ff5/UI/Module/Estimation/Model/MCMC/McmcChain.cs#L611).

The code doesn't take into account duplicate RefNames for observations sets. Curine in this instance.

Fix is to include the set ID in the column name.

**Comment by thehoglet** [comment] 2019-12-31 17:52
Fixed in v0.9.

**Closed as completed by thehoglet** 2019-12-31 17:52 UTC
Labels: bug
